ProjectOrder:
  type: input-object
  config:
    description: Ways in which projects can be ordered
    fields:
      field:
        type: ProjectOrderField!
        description: The field in which to order the projects by
      direction:
        type: OrderDirection!
        defaultValue: ASC
        description: The direction in which to order the projects
